
BASE_DMA          = DMAF_SETCLR|DMAF_MASTER|DMAF_COPPER|DMAF_BLITTER|DMAF_RASTER

SCREEN_WIDTH      = 320
SCREEN_WIDTH_BYTE = SCREEN_WIDTH/8
SCREEN_HEIGHT     = 256
SCREEN_DEPTH      = 5
SCREEN_MOD        = SCREEN_WIDTH_BYTE*(SCREEN_DEPTH-1)
SCREEN_SIZE       = SCREEN_WIDTH_BYTE*SCREEN_HEIGHT*SCREEN_DEPTH
SCREEN_STRIDE     = SCREEN_DEPTH*SCREEN_WIDTH_BYTE
SCREEN_COLORS     = 32