
BASE_DMA           = DMAF_SETCLR|DMAF_MASTER|DMAF_COPPER|DMAF_BLITTER|DMAF_RASTER

WINDOW_X_START     = $81-16
WINDOW_X_STOP      = $c1
WINDOW_Y_START     = $2c
WINDOW_Y_STOP      = $2c

WINDOW_START       = (WINDOW_Y_START<<8)|WINDOW_X_START
WINDOW_STOP        = (WINDOW_Y_STOP<<8)|WINDOW_X_STOP
FETCH_START        = $38-8
FETCH_STOP         = $d0

SCREEN_WIDTH       = TILE_WIDTH*WALL_PAPER_WIDTH
SCREEN_WIDTH_BYTE  = SCREEN_WIDTH/8
SCREEN_HEIGHT      = TILE_HEIGHT*WALL_PAPER_HEIGHT
SCREEN_DEPTH       = 5
SCREEN_MOD         = SCREEN_WIDTH_BYTE*(SCREEN_DEPTH-1)
SCREEN_SIZE        = SCREEN_WIDTH_BYTE*SCREEN_HEIGHT*SCREEN_DEPTH
SCREEN_STRIDE      = SCREEN_DEPTH*SCREEN_WIDTH_BYTE
SCREEN_COLORS      = 32

DIW_XSTRT          = ($242-SCREEN_WIDTH)/2
DIW_YSTRT          = ($158-SCREEN_HEIGHT)/2
DIW_XSTOP          = DIW_XSTRT+SCREEN_WIDTH
DIW_YSTOP          = DIW_YSTRT+SCREEN_HEIGHT

WALL_PAPER_WIDTH   = 14
WALL_PAPER_HEIGHT  = 9
WALL_PAPER_SIZE    = WALL_PAPER_WIDTH*WALL_PAPER_HEIGHT
GAME_MAP_SIZE      = WALL_PAPER_WIDTH*(WALL_PAPER_HEIGHT+1)

MAP_WIDTH          = 11
MAP_HEIGHT         = 8
MAP_SIZE           = MAP_WIDTH*MAP_HEIGHT

BLOCK_EMPTY        = 0
BLOCK_LADDER       = 1
BLOCK_ENEMYFALL    = 2
BLOCK_PUSH         = 3
BLOCK_DIRT         = 4
BLOCK_SOLID        = 5
BLOCK_ENEMYFLOAT   = 6
BLOCK_MILLIESTART  = 7
BLOCK_MOLLYSTART   = 8

TILE_WIDTH         = 24
TILE_HEIGHT        = 24

TILE_WIDTHF        = 32
TILE_SIZE          = (TILE_WIDTHF/8)*SCREEN_DEPTH*TILE_HEIGHT
SHADOW_SIZE        = (TILE_WIDTHF/8)*TILE_HEIGHT

TILE_SCREEN_WIDTH  = SCREEN_WIDTH/TILE_WIDTH
TILE_SCREEN_HEIGHT = SCREEN_HEIGHT/TILE_HEIGHT

START_LEVEL        = 0

SPRITESET_COUNT    = 12*12
SPRITESET_SIZE     = TILE_SIZE*SPRITESET_COUNT
TILESET_SIZE       = TILE_SIZE*TILESET_COUNT
TILESET_COUNT      = 8*4

KEY_F1             = $50
KEY_F2             = $51
KEY_F3             = $52
KEY_F4             = $53
KEY_F5             = $54
KEY_F6             = $55
KEY_F7             = $56
KEY_F8             = $57
KEY_F9             = $58
KEY_F10            = $59
